### ISSUE TITLE
Compatibility with typescript

### ISSUE THREAD

**Issue by Annmary12** [tonix-tuft/moment-utl#3]
Currently, this package is not compatible with typescript. Is there a plan to release the typescript version?

**Comment by tonix-tuft** [comment]
> Is there a plan to release the typescript version?

No, not for now, maybe in the future. Are you experiencing issues when you are using it in a TypeScript project?

Which issue are you facing?

**Comment by Annmary12** [comment]
Yes, I am having typescript problems. 
Here is the screen shot 

<img width="740" alt="Screen Shot 2020-07-31 at 11 30 53 AM" src="https://user-images.githubusercontent.com/14803275/89026870-544dfc80-d321-11ea-8aaf-527fb8a2a91b.png">

**Comment by tonix-tuft** [comment]
As far as I know, this is just a warning and your code using `allSupportedLocales` should work.

If you know a way to remove this warning from VS Code without having to translate the project to TypeScript, tell me and I will do it (maybe the `.d.ts` file mentioned in the warning could be a solution, but I do not know what it means).

**Comment by Annmary12** [comment]
It is actually not a warning, it is breaking my application.

**Comment by tonix-tuft** [comment]
OK. Will check this on a sample TypeScript project and let you know.

**Comment by tonix-tuft** [comment]
It works here on this [codesandbox](https://codesandbox.io/s/typescript-pv5qy?file=/src/index.ts) (even though there is still the annoying warning).

What do you mean by `breaking my application`?  Does the TypeScript compiler compiles the project and you get a runtime error, or what?

I will also try to use `moment-utl` in a React TypeScript template project.
Meanwhile, if you find a way to inhibit the warning, that would be useful.

Thank you!

**Comment by Annmary12** [comment]
I am using TypeScript compiler to compile my project. I used this [article](https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/) to create a workaround

**Comment by tonix-tuft** [comment]
> I am using TypeScript compiler to compile my project. I used this [article](https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/) to create a workaround

OK, but which type of issue are you facing? Is it a compile issue or runtime? Can you post a screenshot? Thank you!

**Comment by Annmary12** [comment]
Compilation issue, the error message is the same as the one I sent earlier

**Comment by tonix-tuft** [comment]
OK, will try to reproduce it.

**Comment by tonix-tuft** [comment]
Hello @Annmary12!

I have reproduced your issue in a local TypeScript project.

I have added an `index.d.ts` file in version `2.13.1`.
Can you try updating to this version with `npm update` or `yarn update` (if you are using Yarn), remove the workaround you added and see if your project builds?

My local test builds and if I `Cmd+click` on a function of `moment-utl` VS Code sends me to the `index.d.ts` file to the definition of that function.

Let me know if it works for you too so I will close this issue.

Thanks!

**Comment by Annmary12** [comment]
I tried it out and it works. Thanks for fixing it.

**Comment by tonix-tuft** [comment]
You're welcome. Closing this issue.
